In [4]:
import numpy
n=numpy.arange(27)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [10]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
m = numpy.asarray([[123, 12, 123,12,33],[],[]])
type(n)

numpy.ndarray

In [22]:
import cv2
type(cv2)

module

In [23]:
img = cv2.imread("original.png", 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
cv2.imwrite("newimage.png", img)

True

In [56]:
img[2, 1:4] = 208
cv2.imwrite("doubleimg.png", img)

True

In [64]:
img[0:,0:]=1
img[0:,0] = 100
img[0:, 4] = 100
img[0, 0:] = 100
img[2, 0:] = 100
print(img)
cv2.imwrite("doubleimg.png", img)

[[100 100 100 100 100]
 [100   1   1   1 100]
 [100 100 100 100 100]]


True

In [69]:
ims = numpy.hstack((img,img))
print(ims)
ims = numpy.vstack((img,img))
print(ims)

[[100 100 100 100 100 100 100 100 100 100]
 [100   1   1   1 100 100   1   1   1 100]
 [100 100 100 100 100 100 100 100 100 100]]
[[100 100 100 100 100]
 [100   1   1   1 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100   1   1   1 100]
 [100 100 100 100 100]]


In [83]:
lms = numpy.vsplit(img,3)
print(lms)
print(img)

[array([[100, 100, 100, 100, 100]], dtype=uint8), array([[100,   1,   1,   1, 100]], dtype=uint8), array([[100, 100, 100, 100, 100]], dtype=uint8)]
[[100 100 100 100 100]
 [100   1   1   1 100]
 [100 100 100 100 100]]
